### ISSUE TITLE
angular-marked-mathjax

### ISSUE THREAD

**Issue by RBleyenberg** [webjars/webjars#1062]
Failed! Version 0.0.14 for path 'webjars/maven/org.webjars.bower:angular-marked-mathjax already exists If you feel you have reached this failure in error, please file an issue: https://github.com/webjars/webjars/issues  Created BinTray Package Converted project licenses Created Bower WebJar Fetched Bower zip Generated POM Converted dependencies to Maven Got Bower info Starting Deploy

**Comment by jamesward** [comment]
That package has already been deployed on Maven Central: https://search.maven.org/#search%7Cga%7C1%7Cangular-marked-mathjax

There is a delay of a few hours between deployment and when something shows up in the Maven Central index and on webjars.org.

**Comment by RBleyenberg** [comment]
Dear James,

On webjar bower you will find "org.webjars.bower" % "angular-marked-mathjax" % "0.0.14".

tho the title is angular-marked and i believe that angular-marked and angular-marked-mathjax are two separate thingies. 

after copy paste this within the sbt file it gives the following error;

Error:Error while importing SBT project:
...
	at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1192)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:42)
	at sbt.std.Transform$$anon$4.work(System.scala:64)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:18)
	at sbt.Execute.work(Execute.scala:244)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:160)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:30)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
[error] sbt.ResolveException: unresolved dependency: org.webjars.bower#marked-mathjax;[0,): not found
[error] Use 'last' for the full log.

This is after a full day,  i did see the repo on maven also yesterday.

Hope you can shine some light on this case.

Best Regards,

**Comment by jamesward** [comment]
This error is saying that the transitive dependency `org.webjars.bower#marked-mathjax;[0,)` can not be found.  I just deployed that library and so it should be available on Maven Central in a few hours.

**Comment by RBleyenberg** [comment]
Woop, that's fast. thx
