### ISSUE TITLE
Add a classic webjar for Polymer Elements All

### ISSUE THREAD

**Issue by bcopy** [webjars/webjars#1522]
Dear James,

Using Polymer Elements from individual webjars has been a living hell for us - Using Bower is not very Java-friendly.
Hence we combined both approaches using the excellent maven-frontend-plugin.

The result is a webjar containing all official Polymer elements and their JS dependencies in a single neat package.

The packaged webjar still contains unnecessary test files and intermediate build definitions, but it'll be a starting point :

https://github.com/CERN/webjars-polymer-elements-all

Thanks,

Brice

**Comment by bcopy** [comment]
@emandil

**Comment by bcopy** [comment]
@emandi

**Comment by jamesward** [comment]
Thanks for putting this together.  From what I can tell the downloads of the Bower artifacts are not versioned.  With WebJars we always use versioned upstream downloads.  Can that be resolved?

Also, where does `maven-frontend-plugin` install Node / NPM to?

**Comment by bcopy** [comment]
Hi,

Sorry versioning polymer elements is like herding cats.... I take drops by
date, as there doesn't seem to be any coherent official versioning, only
individual ones that get resolved by bower.

Node and npm end up under target, but node_components for bower under the
working maven directory (due to a known limitation in the plugin) hence the
.gitignore.

**Comment by jamesward** [comment]
Without versioning we essentially have indeterminate artifact resolution because it depends on when I run `mvn release` and there is no way to know the correlation between the WebJar version and any point-in-time in the upstream projects.  To work around this with other WebJars we sometimes have to use commit ids instead of tags.  I'd rather not break our artifact versioning standard we currently have in place for WebJars.

**Comment by bcopy** [comment]
Commit ids okay but git repository would you base it upon ?
I've tossed and turned this problem and I've come to this conclusion. I'm
open to suggestions.

**Comment by jamesward** [comment]
Can't you just add git tags or commit ids to the `bower.json` so that it resolves a specific version of the upstream artifact?

**Comment by jamesward** [comment]
The other alternative would be to just release `SNAPSHOT` versions since those are expected to be mutable / indeterminate.

**Comment by bcopy** [comment]
@jamesward : I get your point, the element collections do have a version number, and while I can't find a coherent version set anywhere for the entire list of element collections, I trust that bower can resolve this properly and that the Polymer team have such information somewhere.

So I updated the bower.json accordingly, I hope it's okay now.

**Comment by jamesward** [comment]
That is looking better.  Thanks!  One last thing...  I think we should go with a version like `0.0.1` or something instead of the date based version.  Is that ok?

**Comment by bcopy** [comment]
Hi James,

I didn't want to use a conventional version number because I don't want to
give the impression that we're offering a coherent set of dependencies.
I didn't want to use a SNAPSHOT suffix, but it'll force unnecessary
refreshes in maven.

However, if you want to start the numbering at 0.0.1 it's okay for me too.
People will just have to read the README

Cheers,

Brice

**Comment by jamesward** [comment]
Yeah, we don't need to do a `SNAPSHOT` but we need that in the `pom.xml` because Maven will do the actual release.

I've forked and updated the `pom.xml` and will do a release shortly.  Here is the fork:
https://github.com/webjars/polymer-elements-all

Thanks for putting this together!

**Comment by jamesward** [comment]
I'm having some issues doing the release related to `frontend-maven-plugin`.  Here is the log:
```
$ mvn release:prepare release:perform
[INFO] Scanning for projects...
[INFO] Inspecting build with total of 1 modules...
[INFO] Installing Nexus Staging features:
[INFO]   ... total of 1 executions of maven-deploy-plugin replaced with nexus-staging-maven-plugin
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building polymer-elements-all 0.0.2-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-release-plugin:2.5.3:prepare (default-cli) @ polymer-elements-all ---
[INFO] Release preparation already completed. You can now continue with release:perform, or start again using the -Dresume=false flag
[INFO] 
[INFO] --- maven-release-plugin:2.5.3:perform (default-cli) @ polymer-elements-all ---
[INFO] Checking out the project to perform the release ...
[INFO] Executing: /bin/sh -c cd /Volumes/Home/j.ward/projects/webjars/polymer-elements-all/target && git clone --branch polymer-elements-all-0.0.1 https://github.com/webjars/polymer-elements-all.git /Volumes/Home/j.ward/projects/webjars/polymer-elements-all/target/checkout
[INFO] Working directory: /Volumes/Home/j.ward/projects/webjars/polymer-elements-all/target
[INFO] Executing: /bin/sh -c cd /var/folders/bm/lqwtdtyj05qdtbm8fdt81sy9fkfzl9/T/ && git ls-remote https://github.com/webjars/polymer-elements-all.git
[INFO] Working directory: /var/folders/bm/lqwtdtyj05qdtbm8fdt81sy9fkfzl9/T
[INFO] Executing: /bin/sh -c cd /Volumes/Home/j.ward/projects/webjars/polymer-elements-all/target/checkout && git fetch https://github.com/webjars/polymer-elements-all.git
[INFO] Working directory: /Volumes/Home/j.ward/projects/webjars/polymer-elements-all/target/checkout
[INFO] Executing: /bin/sh -c cd /Volumes/Home/j.ward/projects/webjars/polymer-elements-all/target/checkout && git checkout polymer-elements-all-0.0.1
[INFO] Working directory: /Volumes/Home/j.ward/projects/webjars/polymer-elements-all/target/checkout
[INFO] Executing: /bin/sh -c cd /Volumes/Home/j.ward/projects/webjars/polymer-elements-all/target/checkout && git ls-files
[INFO] Working directory: /Volumes/Home/j.ward/projects/webjars/polymer-elements-all/target/checkout
[INFO] Invoking perform goals in directory /Volumes/Home/j.ward/projects/webjars/polymer-elements-all/target/checkout
[INFO] Executing goals 'deploy'...
[INFO] Executing: /bin/sh -c cd /Volumes/Home/j.ward/projects/webjars/polymer-elements-all/target/checkout && /usr/local/Cellar/maven/3.3.9/libexec/bin/mvn -s /var/folders/bm/lqwtdtyj05qdtbm8fdt81sy9fkfzl9/T/release-settings9194806888606985079.xml deploy --no-plugin-updates -Psonatype-oss-release -f pom.xml
    [WARNING] Command line option -npu is deprecated and will be removed in future Maven versions.
    [INFO] Scanning for projects...
    [INFO] Inspecting build with total of 1 modules...
    [INFO] Installing Nexus Staging features:
    [INFO]   ... total of 1 executions of maven-deploy-plugin replaced with nexus-staging-maven-plugin
    [INFO]                                                                         
    [INFO] ------------------------------------------------------------------------
    [INFO] Building polymer-elements-all 0.0.1
    [INFO] ------------------------------------------------------------------------
    [INFO] 
    [INFO] --- maven-enforcer-plugin:1.0:enforce (enforce-maven) @ polymer-elements-all ---
    [INFO] 
    [INFO] --- unsnapshot-maven-plugin:0.2:unsnapshot (default) @ polymer-elements-all ---
    [INFO] 
    [INFO] --- frontend-maven-plugin:1.3:install-node-and-npm (install node and npm) @ polymer-elements-all ---
    [INFO] Installing node version v4.6.0
    [INFO] Unpacking /Volumes/Home/j.ward/.m2/repository/com/github/eirslett/node/4.6.0/node-4.6.0-darwin-x64.tar.gz into /Volumes/Home/j.ward/projects/webjars/polymer-elements-all/target/checkout/target/node/tmp
    [INFO] Copying node binary from /Volumes/Home/j.ward/projects/webjars/polymer-elements-all/target/checkout/target/node/tmp/node-v4.6.0-darwin-x64/bin/node to /Volumes/Home/j.ward/projects/webjars/polymer-elements-all/target/checkout/target/node/node
    [INFO] Installed node locally.
    [INFO] Installing npm version 2.15.9
    [INFO] Unpacking /Volumes/Home/j.ward/.m2/repository/com/github/eirslett/npm/2.15.9/npm-2.15.9.tar.gz into /Volumes/Home/j.ward/projects/webjars/polymer-elements-all/target/checkout/target/node/node_modules
    [INFO] Installed npm locally.
    [INFO] 
    [INFO] --- frontend-maven-plugin:1.3:npm (npm bower install) @ polymer-elements-all ---
    [INFO] Running 'npm install bower' in /Volumes/Home/j.ward/projects/webjars/polymer-elements-all/target/checkout
    [INFO] bower@1.8.0 ../../node_modules/bower
    [INFO] 
    [INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ polymer-elements-all ---
    [INFO] Using 'UTF-8' encoding to copy filtered resources.
    [INFO] skip non existing resourceDirectory /Volumes/Home/j.ward/projects/webjars/polymer-elements-all/target/checkout/src/main/resources
    [INFO] 
    [INFO] --- frontend-maven-plugin:1.3:bower (bower install) @ polymer-elements-all ---
    [INFO] Running 'bower install' in /Volumes/Home/j.ward/projects/webjars/polymer-elements-all/target/checkout
    [ERROR] module.js:327
    [ERROR]     throw err;
    [ERROR]     ^
    [ERROR] 
    [ERROR] Error: Cannot find module '/Volumes/Home/j.ward/projects/webjars/polymer-elements-all/target/checkout/node_modules/bower/bin/bower'
    [ERROR]     at Function.Module._resolveFilename (module.js:325:15)
    [ERROR]     at Function.Module._load (module.js:276:25)
    [ERROR]     at Function.Module.runMain (module.js:441:10)
    [ERROR]     at startup (node.js:139:18)
    [ERROR]     at node.js:974:3
    [INFO] ------------------------------------------------------------------------
    [INFO] BUILD FAILURE
    [INFO] ------------------------------------------------------------------------
    [INFO] Total time: 13.502 s
    [INFO] Finished at: 2016-12-09T16:00:40-07:00
    [INFO] Final Memory: 19M/356M
    [INFO] ------------------------------------------------------------------------
    [ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.3:bower (bower install) on project polymer-elements-all: Failed to run task: 'bower install' failed. (error code 1) -> [Help 1]
    [ERROR] 
    [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
    [ERROR] Re-run Maven using the -X switch to enable full debug logging.
    [ERROR] 
    [ERROR] For more information about the errors and possible solutions, please read the following articles:
    [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 21.928 s
[INFO] Finished at: 2016-12-09T16:00:40-07:00
[INFO] Final Memory: 14M/220M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-release-plugin:2.5.3:perform (default-cli) on project polymer-elements-all: Maven execution failed, exit code: '1' -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

Oddly everything works fine when I do `mvn package` so I'm not sure what the problem is.

**Comment by bcopy** [comment]
Hi @jamesward 

Sorry about that, I think the installDirectory configuration option in the frontend plugin does not play well with the release perform.
Pull request incoming.

**Comment by bcopy** [comment]
Reported to frontend plugin team in https://github.com/eirslett/frontend-maven-plugin/issues/539
