### ISSUE TITLE
generator for NPM webjars names them so dependancies don't match up

### ISSUE THREAD

**Issue by jehrlich** [webjars/webjars#1534]
Creating a NPM webjar from a github URL using the web paqge interface, for example 
`"org.webjars.npm" % "github-com-moroshko-react-autosuggest" % "7.0.2"` creates an artifact ID like

 ```
GroupID = org.webjars.npm
ArtifactID = github-com-moroshko-react-autosuggest
Version = 7.0.2

```
 but dependancies are identified without the github URL. For example using the above jar in Play Framework with RequireJS yields this compile error:

```
 downloading https://repo1.maven.org/maven2/org/webjars/npm/github-com-moroshko-react-autosuggest/7.0.2/github-com-moroshko-react-autosuggest-7.0.2.jar ...
[info] 	[SUCCESSFUL ] org.webjars.npm#github-com-moroshko-react-autosuggest;7.0.2!github-com-moroshko-react-autosuggest.jar (1246ms)
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: org.webjars.npm#react-autowhatever;[7.0.0,8): not found
[warn] 	:: org.webjars.npm#react-redux;[5.0.1,6): not found
[warn] 	:: org.webjars.npm#shallow-equal;[1.0.0,2): not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 
[warn] 	Note: Unresolved dependencies path:
[warn] 		org.webjars.npm:react-autowhatever:[7.0.0,8)
[warn] 		  +- org.webjars.npm:github-com-moroshko-react-autosuggest:7.0.2 (/Users/jimehrlich/IdeaProjects/protManager/build.sbt#L27-56)
[warn] 		  +- vcpr-protocols-manager:vcpr-protocols-manager_2.11:1.0.5
[warn] 		org.webjars.npm:react-redux:[5.0.1,6)
[warn] 		  +- org.webjars.npm:github-com-moroshko-react-autosuggest:7.0.2 (/Users/jimehrlich/IdeaProjects/protManager/build.sbt#L27-56)
[warn] 		  +- vcpr-protocols-manager:vcpr-protocols-manager_2.11:1.0.5
[warn] 		org.webjars.npm:shallow-equal:[1.0.0,2)
[warn] 		  +- org.webjars.npm:github-com-moroshko-react-autosuggest:7.0.2 (/Users/jimehrlich/IdeaProjects/protManager/build.sbt#L27-56)
[warn] 		  +- vcpr-protocols-manager:vcpr-protocols-manager_2.11:1.0.5
sbt.ResolveException: unresolved dependency: org.webjars.npm#react-autowhatever;[7.0.0,8): not found
unresolved dependency: org.webjars.npm#react-redux;[5.0.1,6): not found
unresolved dependency: org.webjars.npm#shallow-equal;[1.0.0,2): not found
	at sbt.IvyActions$.sbt$IvyActions$$resolve(IvyActions.scala:313)
	at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:191)
	at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:168)
	at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:156)
	at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:156)
	at sbt.IvySbt$$anonfun$withIvy$1.apply(Ivy.scala:133)
	at sbt.IvySbt.sbt$IvySbt$$action$1(Ivy.scala:57)
	at sbt.IvySbt$$anon$4.call(Ivy.scala:65)
	at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:93)
	at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:78)
	at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:97)
	at xsbt.boot.Using$.withResource(Using.scala:10)
	at xsbt.boot.Using$.apply(Using.scala:9)
	at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:58)
	at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:48)
	at xsbt.boot.Locks$.apply0(Locks.scala:31)
	at xsbt.boot.Locks$.apply(Locks.scala:28)
	at sbt.IvySbt.withDefaultLogger(Ivy.scala:65)
	at sbt.IvySbt.withIvy(Ivy.scala:128)
	at sbt.IvySbt.withIvy(Ivy.scala:125)
	at sbt.IvySbt$Module.withModule(Ivy.scala:156)
	at sbt.IvyActions$.updateEither(IvyActions.scala:168)
	at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1439)
	at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1435)
	at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$90.apply(Defaults.scala:1470)
	at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$90.apply(Defaults.scala:1468)
	at sbt.Tracked$$anonfun$lastOutput$1.apply(Tracked.scala:37)
	at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1473)
	at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1467)
	at sbt.Tracked$$anonfun$inputChanged$1.apply(Tracked.scala:60)
	at sbt.Classpaths$.cachedUpdate(Defaults.scala:1490)
	at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1417)
	at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1369)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:237)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[error] (*:update) sbt.ResolveException: unresolved dependency: org.webjars.npm#react-autowhatever;[7.0.0,8): not found
[error] unresolved dependency: org.webjars.npm#react-redux;[5.0.1,6): not found
[error] unresolved dependency: org.webjars.npm#shallow-equal;[1.0.0,2): not found
 

```
Since I also created an aurowhatever jar in the same manner, it exists as 
`"org.webjars.npm" % "github-com-moroshko-react-autowhatever" % "7.0.0"` but the required dependancy is named  `org.webjars.npm#react-autowhatever;[7.0.0,8):` without the github prefix.

**Comment by jamesward** [comment]
You can deploy NPM WebJars either using a git repo or a name from the NPM registry.  The name for the generated artifact depends on which way you picked.  So to generate the `react-autowhatever` artifact, specify that name in the input field.  Let me know if that doesn't work.

**Comment by jehrlich** [comment]
Thank you. This got me started. I created webjars using the the name from the NPM registry, and they compile. From my build.sbt, Play 2.5
```
  "org.webjars" %% "webjars-play" % "2.5.0", //http://www.webjars.org/documentation
  "org.webjars" % "jquery" % "2.2.4",
  "org.webjars" % "requirejs" % "2.3.2", //was 2.3.1
  "org.webjars" % "react" % "15.3.2", // 15.1.0",
  "org.webjars.npm" % "react-dom" % "15.1.0",
  "org.webjars.npm" % "react-autosuggest" % "8.0.0",
```
I think I followed directions from http://www.webjars.org/documentation except that `@Html(requireJS.setup(routes.Assets.versioned("javascripts/editor.js")))` is in the body of a template, not the head. The page loads folders for each webjar, but the folder labeled `webjars/react-autosuggest/8.0.0/dist` only contains a single short file, index.js
```
'use strict';
module.exports = require('./Autosuggest').default;
```
The target directory of my app contains the full react-autosuggest folder structure and code. The browser's javascript error is 
`index.js:3 Uncaught ReferenceError: module is not defined  at index.js:3
`
My supposition is that something needs to tell the browser to load the module code, but what? Where?



![screen shot 2017-01-17 at 1 06 55 pm](https://cloud.githubusercontent.com/assets/1613775/22033439/7bc26914-dcb6-11e6-98d9-4d03b5650807.png)


![screen shot 2017-01-17 at 12 11 50 pm](https://cloud.githubusercontent.com/assets/1613775/22033471/9ab1e37c-dcb6-11e6-9bfb-3a817fa82599.png)

**Comment by jamesward** [comment]
Hmm. I'm not sure if that is due to a problem with the `react-autosuggest` WebJar packaging.  Can you check to see if it is missing something?

**Comment by jehrlich** [comment]
It looks to me like all the files are in the webjar, 
```
META-INF/resources/webjars/react-autosuggest/8.0.0/package.json
META-INF/resources/webjars/react-autosuggest/8.0.0/README.md
META-INF/resources/webjars/react-autosuggest/8.0.0/LICENSE
META-INF/resources/webjars/react-autosuggest/8.0.0/dist/Autosuggest.js
META-INF/resources/webjars/react-autosuggest/8.0.0/dist/index.js
META-INF/resources/webjars/react-autosuggest/8.0.0/dist/standalone/autosuggest.js
META-INF/resources/webjars/react-autosuggest/8.0.0/dist/standalone/autosuggest.min.js
```
but the browser only loads the index.js with the module.exports line. With so much magic in the Play assets pipeline and webjars and requireJS, I'm unclear what is needed. Perhaps I need some manual config of requireJS so that it loads the full directory tree of the jar?

**Comment by jamesward** [comment]
Looking closer at the error it seems like it is due to RequireJS not being loaded or something.  I'm not a RequireJS expert so I'm not sure how to go about troubleshooting this.  And unfortunately I've had a lot of challenges with RequireJS.  But the WebJars all seem to be correct so I think you'll have to go down the RequireJS debugging path or ditch it.

**Comment by jehrlich** [comment]
Thanks. My current hypothesis is that this has to do with differences in ways modules are defined for NMN, AMD, .... Whether this is a webjars issue is a question of where the boundary is on "supports requirejs out of the box" It would be nice if the packager was smart enough to universalize module definitions.

[This post](https://github.com/primus/eventemitter3/issues/49) suggests a possible solution:

> Can we please include a proper way to define the module, so it actually starts working everywhere? Something like:
> 

```
(function (name, definition){
    if (typeof define === 'function'){ // AMD
        define(definition);
    } else if (typeof module !== 'undefined' && module.exports) { // Node.js
        module.exports = definition(require);
    } else { // Browser
        var theModule = definition(), global = this, old = global[name];
        theModule.noConflict = function () {
            global[name] = old;
            return theModule;
        };
        global[name] = theModule;
    }
})('EventEmitter3', function (require, exports, module) {
    // the real code here
}); 
Can we please include a proper way to define the module, so it actually starts working everywhere? Something like:

(function (name, definition){
    if (typeof define === 'function'){ // AMD
        define(definition);
    } else if (typeof module !== 'undefined' && module.exports) { // Node.js
        module.exports = definition(require);
    } else { // Browser
        var theModule = definition(), global = this, old = global[name];
        theModule.noConflict = function () {
            global[name] = old;
            return theModule;
        };
        global[name] = theModule;
    }
})('EventEmitter3', function (require, exports, module) {
    // the real code here
});  
```
I'm not sure if it is feasible to have the webjars packager take on this little additional piece of magic.

**Comment by jamesward** [comment]
yikes.  I'm not sure where would be the right place to put that.  The JS module loading stuff is a total mess.  :(

**Comment by fourpixels** [comment]
This is pretty straightforward and used solution all around the globe :) Currently this package doesn't work for AMD.
