### ISSUE TITLE
TimerTask Exception during deployment

### ISSUE THREAD

**Issue by binhbbui411** [webjars/webjars#1757]
I ran to this problem during deploying [px-accordion](https://github.com/predixdesignsystem/px-accordion).  

 > [[33mwarn[0m] p.s.a.i.n.u.HashedWheelTimer - An exception was thrown by TimerTask.
java.lang.IllegalStateException: cannot be started once stopped
	at play.shaded.ahc.io.netty.util.HashedWheelTimer.start(HashedWheelTimer.java:338)
	at play.shaded.ahc.io.netty.util.HashedWheelTimer.newTimeout(HashedWheelTimer.java:417)
	at play.shaded.ahc.org.asynchttpclient.netty.channel.DefaultChannelPool.scheduleNewIdleChannelDetector(DefaultChannelPool.java:96)
	at play.shaded.ahc.org.asynchttpclient.netty.channel.DefaultChannelPool.access$1200(DefaultChannelPool.java:39)
	at play.shaded.ahc.org.asynchttpclient.netty.channel.DefaultChannelPool$IdleChannelDetector.run(DefaultChannelPool.java:242)
	at play.shaded.ahc.io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:663)
	at play.shaded.ahc.io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:738)
	at play.shaded.ahc.io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:466)
	at java.lang.Thread.run(Thread.java:748)

How may I resolve this?

**Comment by jamesward** [comment]
I've occasionally seen this and need to investigate why this happens sometimes.

**Comment by kalexmills** [comment]
For what it's worth, I saw it when webjars attempted to deploy package `A` from npm when.
1) I had already successfully deployed package `A` via webjars.org in another tab, and
2) package `A` was  not yet showing up in maven central (still waiting for batch index update?)
