### ISSUE TITLE
bs-custom-file-input-1.3.2.jar is borked

### ISSUE THREAD

**Issue by dashorst** [webjars/webjars#1872]
When trying to use the bs-custom-file-input-1.3.2.jar in my project, I was unable to retrieve the resources from the jar archive. Unzipping the file gave errors, and `jar xf` als results in errors.

```
unzip /Users/dashorst/.m2/repository/org/webjars/npm/bs-custom-file-input/1.3.2/bs-custom-file-input-1.3.2.jar 
Archive:  /Users/dashorst/.m2/repository/org/webjars/npm/bs-custom-file-input/1.3.2/bs-custom-file-input-1.3.2.jar
  inflating: META-INF                
  inflating: maven                   
  inflating: org.webjars.npm         
  inflating: bs-custom-file-input    
checkdir error:  META-INF exists but is not directory
                 unable to process META-INF/maven/org.webjars.npm/bs-custom-file-input/pom.xml.
checkdir error:  META-INF exists but is not directory
                 unable to process META-INF/maven/org.webjars.npm/bs-custom-file-input/pom.properties.
```

and

```
$ jar xf ../bs-custom-file-input-1.3.2.jar 
java.io.IOException: META-INF/maven/org.webjars.npm/bs-custom-file-input : could not create directory
	at jdk.jartool/sun.tools.jar.Main.extractFile(Main.java:1449)
	at jdk.jartool/sun.tools.jar.Main.extract(Main.java:1364)
	at jdk.jartool/sun.tools.jar.Main.run(Main.java:409)
	at jdk.jartool/sun.tools.jar.Main.main(Main.java:1681)
```

**Comment by dashorst** [comment]
1.3.1 does work

**Comment by jamesward** [comment]
I'm deploying `1.3.2-1` now which I think should resolve this.  Let me know.

**Comment by dashorst** [comment]
Works! Thank you! 🥇
