### ISSUE TITLE
jsondiffpath 0.3.11 in org.webjars.npm appears empty

### ISSUE THREAD

**Issue by slohr** [webjars/webjars#1874]
While using "org.webjars.npm" % "jsondiffpatch" % "0.3.11"

The webjar pulled down appears empty:

```
jar -xvf jsondiffpatch-0.3.11.jar
 inflated: META-INF
 inflated: maven
 inflated: org.webjars.npm
 inflated: jsondiffpatch
java.io.IOException: META-INF/maven/org.webjars.npm/jsondiffpatch : could not create directory
	at sun.tools.jar.Main.extractFile(Main.java:1064)
	at sun.tools.jar.Main.extract(Main.java:981)
	at sun.tools.jar.Main.run(Main.java:311)
	at sun.tools.jar.Main.main(Main.java:1288)
```

Version 0.2.4 in org.webjars.bower appears OK, but naturally I want to move away from that one due to the status of bower.

```
jar -xvf jsondiffpatch-0.2.4.jar
  created: META-INF/
  created: META-INF/maven/
  created: META-INF/maven/org.webjars.bower/
  created: META-INF/maven/org.webjars.bower/jsondiffpatch/
 inflated: META-INF/maven/org.webjars.bower/jsondiffpatch/pom.xml
 inflated: META-INF/maven/org.webjars.bower/jsondiffpatch/pom.properties
  created: META-INF/resources/
  created: META-INF/resources/webjars/
  created: META-INF/resources/webjars/jsondiffpatch/
  created: META-INF/resources/webjars/jsondiffpatch/0.2.4/
 inflated: META-INF/resources/webjars/jsondiffpatch/0.2.4/.bowerrc
 inflated: META-INF/resources/webjars/jsondiffpatch/0.2.4/.codeclimate.yml
...
```

**Comment by jamesward** [comment]
I'm releasing `0.3.11-1` now which should fix this.  Sorry about the hassle.
