### ISSUE TITLE
Unable to install a dependency in my `sbt` (Play) project.

### ISSUE THREAD

**Issue by igreulich** [webjars/webjars#1905]
I deployed a new WebJar, @talloinc/celula v0.4.0, and during installation into my Play progect (`sbt run`) I get the following error:

```
[warn] 	module not found: org.webjars.npm#js-tokens;[3.0.0,4),[4.0.0,5)
[warn] ==== local: tried
[warn]   /Users/igreulich/.ivy2/local/org.webjars.npm/js-tokens/[3.0.0,4),[4.0.0,5)/ivys/ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/org/webjars/npm/js-tokens/[3.0.0,4),[4.0.0,5)/js-tokens-[3.0.0,4),[4.0.0,5).pom
[warn] ==== local-preloaded-ivy: tried
[warn]   /Users/igreulich/.sbt/preloaded/org.webjars.npm/js-tokens/[3.0.0,4),[4.0.0,5)/ivys/ivy.xml
[warn] ==== local-preloaded: tried
[warn]   file:////Users/igreulich/.sbt/preloaded/org/webjars/npm/js-tokens/[3.0.0,4),[4.0.0,5)/js-tokens-[3.0.0,4),[4.0.0,5).pom
[warn] ==== Clojars Repository: tried
[warn]   http://clojars.org/repo/org/webjars/npm/js-tokens/[3.0.0,4),[4.0.0,5)/js-tokens-[3.0.0,4),[4.0.0,5).pom
[warn] ==== Spy Repository: tried
[warn]   http://files.couchbase.com/maven2/org/webjars/npm/js-tokens/[3.0.0,4),[4.0.0,5)/js-tokens-[3.0.0,4),[4.0.0,5).pom
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: org.webjars.npm#js-tokens;[3.0.0,4),[4.0.0,5): not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn]
[warn] 	Note: Unresolved dependencies path:
[warn] 		org.webjars.npm:js-tokens:[3.0.0,4),[4.0.0,5)
[warn] 		  +- org.webjars.npm:loose-envify:[1.4.0,2)
[warn] 		  +- org.webjars.npm:prop-types:[15.5.10,16)
[warn] 		  +- org.webjars.npm:react-modal:[3.12.1,4)
[warn] 		  +- org.webjars.npm:talloinc__celula:0.4.0 (/Users/igreulich/apps/STEMPremier/build.sbt#L25-115)
[warn] 		  +- com.stempremier:stempremier_2.11:1.0-SNAPSHOT
[error] sbt.librarymanagement.ResolveException: unresolved dependency: org.webjars.npm#js-tokens;[3.0.0,4),[4.0.0,5): not found
[error] 	at sbt.internal.librarymanagement.IvyActions$.resolveAndRetrieve(IvyActions.scala:332)
[error] 	at sbt.internal.librarymanagement.IvyActions$.$anonfun$updateEither$1(IvyActions.scala:208)
[error] 	at sbt.internal.librarymanagement.IvySbt$Module.$anonfun$withModule$1(Ivy.scala:239)
[error] 	at sbt.internal.librarymanagement.IvySbt.$anonfun$withIvy$1(Ivy.scala:204)
[error] 	at sbt.internal.librarymanagement.IvySbt.sbt$internal$librarymanagement$IvySbt$$action$1(Ivy.scala:70)
[error] 	at sbt.internal.librarymanagement.IvySbt$$anon$3.call(Ivy.scala:77)
[error] 	at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:95)
[error] 	at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:80)
[error] 	at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:99)
[error] 	at xsbt.boot.Using$.withResource(Using.scala:10)
[error] 	at xsbt.boot.Using$.apply(Using.scala:9)
[error] 	at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:60)
[error] 	at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:50)
[error] 	at xsbt.boot.Locks$.apply0(Locks.scala:31)
[error] 	at xsbt.boot.Locks$.apply(Locks.scala:28)
[error] 	at sbt.internal.librarymanagement.IvySbt.withDefaultLogger(Ivy.scala:77)
[error] 	at sbt.internal.librarymanagement.IvySbt.withIvy(Ivy.scala:199)
[error] 	at sbt.internal.librarymanagement.IvySbt.withIvy(Ivy.scala:196)
[error] 	at sbt.internal.librarymanagement.IvySbt$Module.withModule(Ivy.scala:238)
[error] 	at sbt.internal.librarymanagement.IvyActions$.updateEither(IvyActions.scala:193)
[error] 	at sbt.librarymanagement.ivy.IvyDependencyResolution.update(IvyDependencyResolution.scala:20)
[error] 	at sbt.librarymanagement.DependencyResolution.update(DependencyResolution.scala:56)
[error] 	at sbt.internal.LibraryManagement$.resolve$1(LibraryManagement.scala:45)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$12(LibraryManagement.scala:93)
[error] 	at sbt.util.Tracked$.$anonfun$lastOutput$1(Tracked.scala:68)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$19(LibraryManagement.scala:106)
[error] 	at scala.util.control.Exception$Catch.apply(Exception.scala:224)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11(LibraryManagement.scala:106)
[error] 	at sbt.internal.LibraryManagement$.$anonfun$cachedUpdate$11$adapted(LibraryManagement.scala:89)
[error] 	at sbt.util.Tracked$.$anonfun$inputChanged$1(Tracked.scala:149)
[error] 	at sbt.internal.LibraryManagement$.cachedUpdate(LibraryManagement.scala:120)
[error] 	at sbt.Classpaths$.$anonfun$updateTask$5(Defaults.scala:2539)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:40)
[error] 	at sbt.std.Transform$$anon$4.work(System.scala:67)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:269)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error] 	at sbt.Execute.work(Execute.scala:278)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:269)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] (update) sbt.librarymanagement.ResolveException: unresolved dependency: org.webjars.npm#js-tokens;[3.0.0,4),[4.0.0,5): not found
[error] Total time: 42 s, completed Dec 3, 2020 4:46:25 PM
```

However it appears as though all the versions of the dependencies are deployed. This is the output of trying to deploy @talloinc/celula v0.4.0 again:

```
Starting Deploy
Got package info for org.webjars.npm talloinc__celula 0.4.0
Determining dependency graph
Deploying these dependencies: exenv#1.2.2 react-modal#3.12.1 loose-envify#1.4.0 warning#4.0.3 react-lifecycles-compat#3.0.4 prop-types#15.7.2 js-tokens#4.0.0 classnames#2.2.6 react-is#17.0.0-rc.3 object-assign#4.1.1 react-table#7.6.2
Got package info for org.webjars.npm exenv 1.2.2
WebJar org.webjars.npm exenv 1.2.2 has already been deployed
Got package info for org.webjars.npm react-modal 3.12.1
WebJar org.webjars.npm react-modal 3.12.1 has already been deployed
Got package info for org.webjars.npm loose-envify 1.4.0
WebJar org.webjars.npm loose-envify 1.4.0 has already been deployed
Got package info for org.webjars.npm warning 4.0.3
WebJar org.webjars.npm warning 4.0.3 has already been deployed
 
Got package info for org.webjars.npm react-lifecycles-compat 3.0.4
WebJar org.webjars.npm react-lifecycles-compat 3.0.4 has already been deployed
Got package info for org.webjars.npm prop-types 15.7.2
WebJar org.webjars.npm prop-types 15.7.2 has already been deployed
Got package info for org.webjars.npm js-tokens 4.0.0
WebJar org.webjars.npm js-tokens 4.0.0 has already been deployed
Got package info for org.webjars.npm classnames 2.2.6
WebJar org.webjars.npm classnames 2.2.6 has already been deployed
Got package info for org.webjars.npm react-is 17.0.0-rc.3
WebJar org.webjars.npm react-is 17.0.0-rc.3 has already been deployed
 
Got package info for org.webjars.npm object-assign 4.1.1
WebJar org.webjars.npm object-assign 4.1.1 has already been deployed
Got package info for org.webjars.npm react-table 7.6.2
WebJar org.webjars.npm react-table 7.6.2 has already been deployed
WebJar org.webjars.npm talloinc__celula 0.4.0 has already been deployed
```

**Comment by jamesward** [comment]
I believe you are running into: https://github.com/sbt/sbt/issues/2647

**Comment by igreulich** [comment]
Looks like. For the record and future Google Searches , adding:

```
dependencyOverrides += "org.webjars.npm" % "js-tokens" % "4.0.0"
```

to my `build.sbt` seems to have fixed things.
