### ISSUE TITLE
nginx error when depolying a jar from npm.

### ISSUE THREAD

**Issue by igreulich** [webjars/webjars#1906]
I am trying to deploy `@talloapp/celula` v0.4.1 from npm. I get the included error. I have sucessfully 'jarred' several versions of the lib before, up to and including v0.4.0.

```
Starting Deploy
Got package info for org.webjars.npm talloinc__celula 0.4.1
Determining dependency graph
Deploying these dependencies: exenv#1.2.2 react-modal#3.12.1 loose-envify#1.4.0 warning#4.0.3 react-lifecycles-compat#3.0.4 prop-types#15.7.2 js-tokens#4.0.0 classnames#2.2.6 react-is#17.0.0-rc.3 object-assign#4.1.1 react-table#7.6.2
Got package info for org.webjars.npm exenv 1.2.2
WebJar org.webjars.npm exenv 1.2.2 has already been deployed
Got package info for org.webjars.npm react-modal 3.12.1
WebJar org.webjars.npm react-modal 3.12.1 has already been deployed
 
Got package info for org.webjars.npm loose-envify 1.4.0
WebJar org.webjars.npm loose-envify 1.4.0 has already been deployed
Got package info for org.webjars.npm warning 4.0.3
WebJar org.webjars.npm warning 4.0.3 has already been deployed
Got package info for org.webjars.npm react-lifecycles-compat 3.0.4
WebJar org.webjars.npm react-lifecycles-compat 3.0.4 has already been deployed
Got package info for org.webjars.npm prop-types 15.7.2
WebJar org.webjars.npm prop-types 15.7.2 has already been deployed
 
Got package info for org.webjars.npm js-tokens 4.0.0
WebJar org.webjars.npm js-tokens 4.0.0 has already been deployed
 
Got package info for org.webjars.npm classnames 2.2.6
WebJar org.webjars.npm classnames 2.2.6 has already been deployed
[[33mwarn[0m] p.s.a.i.n.u.HashedWheelTimer - An exception was thrown by TimerTask.
java.lang.IllegalStateException: cannot be started once stopped
	at play.shaded.ahc.io.netty.util.HashedWheelTimer.start(HashedWheelTimer.java:348)
	at play.shaded.ahc.io.netty.util.HashedWheelTimer.newTimeout(HashedWheelTimer.java:427)
	at play.shaded.ahc.org.asynchttpclient.netty.channel.DefaultChannelPool.scheduleNewIdleChannelDetector(DefaultChannelPool.java:95)
	at play.shaded.ahc.org.asynchttpclient.netty.channel.DefaultChannelPool.access$900(DefaultChannelPool.java:43)
	at play.shaded.ahc.org.asynchttpclient.netty.channel.DefaultChannelPool$IdleChannelDetector.run(DefaultChannelPool.java:378)
	at play.shaded.ahc.io.netty.util.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:680)
	at play.shaded.ahc.io.netty.util.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:755)
	at play.shaded.ahc.io.netty.util.HashedWheelTimer$Worker.run(HashedWheelTimer.java:483)
	at play.shaded.ahc.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
 
Got package info for org.webjars.npm react-is 17.0.0-rc.3
WebJar org.webjars.npm react-is 17.0.0-rc.3 has already been deployed
Got package info for org.webjars.npm object-assign 4.1.1
WebJar org.webjars.npm object-assign 4.1.1 has already been deployed
Got package info for org.webjars.npm react-table 7.6.2
WebJar org.webjars.npm react-table 7.6.2 has already been deployed
Resolving licenses & dependencies for org.webjars.npm talloinc__celula 0.4.1
Resolved Licenses: LGPL-3.0
Converted dependencies to Maven
Converted optional dependencies to Maven
Got the source URL: https://github.com/STEMPremier/celula
Generated POM
Fetched NPM zip
Created NPM WebJar
Created BinTray Package
Created BinTray Version



405 Not Allowed

nginx

```

**Comment by jamesward** [comment]
I believe this was a temporary issue with Maven Central.  I've synced it and it should be available in a few hours.  Let me know if you continue to run into issues.

**Comment by igreulich** [comment]
At the time of this comment, ~3pm, the jar is not available.

**Comment by jamesward** [comment]
Shoot.  Trying again...

**Comment by igreulich** [comment]
For what it is worth, I tried deploying it again, right after I left the previous message, and it 405'ed again.

**Comment by jamesward** [comment]
I think this is actually due to something on BinTray.  Investigating.  Sorry for the hassle!

**Comment by igreulich** [comment]
No worries! And thanks!

**Comment by igreulich** [comment]
So I have a workaround for my situation, but It would still be good to know what's going on, just to be able to get it released in general.

**Comment by jamesward** [comment]
Cool. I had to open a support request with BinTray for this because the artifact upload to them is what is failing. I'll keep you updated.

**Comment by jamesward** [comment]
I was able to release the new `0.4.2` version.  Let me know if you have any issues.
