### ISSUE TITLE
OutOfMemory fails when trying to deploy firebase 10.13.0.

### ISSUE THREAD

**Issue by sasaki-kouhei** [webjars/webjars#2092]
OutOfMemory fails when trying to deploy firebase 10.13.0.

Could you help us to scale up, etc.?

```
Starting Deploy
Got package info for org.webjars.npm firebase 10.13.0

Determining dependency graph

Uncaught error from thread [application-pekko.actor.default-dispatcher-4]: Java heap space, shutting down JVM since 'pekko.jvm-exit-on-fatal-error' is enabled for ActorSystem[application]

java.lang.OutOfMemoryError: Java heap space
at play.api.libs.json.ImmutableLinkedHashMap$$anon$2.sizeHint(ImmutableLinkedHashMap.scala:72)
at play.api.libs.json.ImmutableLinkedHashMap$$anon$2.addAll(ImmutableLinkedHashMap.scala:85)
at play.api.libs.json.ImmutableLinkedHashMap$$anon$2.addAll(ImmutableLinkedHashMap.scala:67)
at scala.collection.mutable.Growable.$plus$plus$eq(Growable.scala:69)
at scala.collection.mutable.Growable.$plus$plus$eq$(Growable.scala:69)
at play.api.libs.json.ImmutableLinkedHashMap$$anon$2.$plus$plus$eq(ImmutableLinkedHashMap.scala:67)
at play.api.libs.json.JsObject$.createFieldsMap(JsValue.scala:206)
at play.api.libs.json.JsObject$.apply(JsValue.scala:212)
at play.api.libs.json.jackson.JsValueDeserializer.deserialize(JacksonJson.scala:228)
at play.api.libs.json.jackson.JsValueDeserializer.deserialize(JacksonJson.scala:158)
at play.api.libs.json.jackson.JsValueDeserializer.deserialize(JacksonJson.scala:153)
at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323)
at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:4706)
at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2879)
at play.api.libs.json.jackson.JacksonJson.parseJsValue(JacksonJson.scala:296)
at play.api.libs.json.StaticBinding$.parseJsValue(StaticBinding.scala:17)
at play.api.libs.json.Json$.parse(Json.scala:175)
at play.api.libs.ws.JsonBodyReadables.$anonfun$readableAsJson$1(JsonBodyReadables.scala:27)
at play.api.libs.ws.JsonBodyReadables$$Lambda/0x00007fa29071d690.apply(Unknown Source)
at play.api.libs.ws.StandaloneWSResponse.body(StandaloneWSResponse.scala:113)
at play.api.libs.ws.StandaloneWSResponse.body$(StandaloneWSResponse.scala:111)
at play.api.libs.ws.ahc.StandaloneAhcWSResponse.body(StandaloneAhcWSResponse.scala:19)
at play.api.libs.ws.ahc.AhcWSResponse.json(AhcWSResponse.scala:93)
at utils.NPM.$anonfun$versions$1(NPM.scala:81)
at utils.NPM$$Lambda/0x00007fa2907913d8.apply(Unknown Source)
at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:470)
at org.apache.pekko.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:73)
at org.apache.pekko.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:110)
at org.apache.pekko.dispatch.BatchingExecutor$BlockableBatch$$Lambda/0x00007fa29071e790.apply$mcV$sp(Unknown Source)
at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:94)
at org.apache.pekko.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:110)
```

**Comment by jamesward** [comment]
Thanks for reporting! I've reduced the deserialization overhead when parsing the versions. This should be deployed in about 10 minutes and then will retry the deploy.

**Comment by jamesward** [comment]
It appears that this is fixed. Let me know if you have any problems!

**Comment by sasaki-kouhei** [comment]
Thank you! We have confirmed that it is fixed! Best for!

<img width="1718" alt="image" src="https://github.com/user-attachments/assets/6d379bb9-bcec-4a32-b8c1-664e7c76a0b6">
